### ISSUE TITLE
Team Work on Communication and NOTION (Meeting note / Roadmap)

### ISSUE THREAD

**Issue by jalynkyrgyz** [CoDemIT2021/Collaboration-with-Step-by-Step#1]
- [x] #4
- [x]  Совместная работа над обоюдными незавершенными задачами во всех спринтах
- [x]  Командная работа над выставлениями оценок других команд **до 18-00 (21/08/21)**
- [x]  Грамотное и правильное ведение/развитие шаблона - Meeting notes and Roadmap
- [x]  Рассказать о своем прогрессе на тему " Что вы смогли улучшить вместе? " 
21-августа в 21-00

**Comment by AzamatZhamankulov** [comment]
all done
